version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - npm install aws-cdk -g
      - yarn install
  build:
    commands:
      - yarn build
      - yarn cdk synth
      - yarn cdk deploy
