version: 0.2
env:
  shell: bash
  variables:
    PGDATABASE: test
  secrets-manager:
    PGUSER: DoorwayTestDbStackSecretCC3-dUp1tGcD6zhb:username
    PGPASSWORD: DoorwayTestDbStackSecretCC3-dUp1tGcD6zhb:password
    PGHOST: DoorwayTestDbStackSecretCC3-dUp1tGcD6zhb:host

phases:
  install:
    commands:
      - npm install aws-cdk -g
      - yarn install
      - sudo yum install -y postgresql15
  build:
    commands:
      - export DATABASE_URL="postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432"
      - echo "DATABASE_URL=${DATABASE_URL}" >> .env
      - yarn build
      - yarn prisma migrate dev --name init
      - yarn cdk synth
      - yarn cdk deploy
